pipeline {
    agent any
    
    environment {
        DOCKER_HUB_CREDS = credentials('dockerhub-creds') // Jenkins credentials ID for Docker Hub
        DOCKER_IMAGE = "naveenbalagouni/my-python-app"
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Checkout the code from GitHub
                git 'https://github.com/NaveenBalagouni/ssd-pratice.git'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    // Login to Docker Hub
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh """
                            echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin
                            docker build -t \$DOCKER_IMAGE:latest .
                        """
                    }
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh """
                            docker push \$DOCKER_IMAGE:latest
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            // Clean up after the build
            cleanWs()
        }
        success {
            echo 'Docker image built and pushed successfully!'
        }
        failure {
            echo 'There was an error during the build or push process.'
        }
    }
}
