pipeline {
  agent {
    kubernetes {
      yamlFile 'path/to/your/pod-template.yaml'
    }
  }
  stages {
    stage('Check Docker') {
      steps {
        container('docker') {
          sh 'docker --version'
        }
      }
    }
  }
}
